jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: ${JENKINS_ADMIN_PASSWORD}
       - id: reader
         password: ${JENKINS_READER_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "USER:Overall/Administer:admin"
        - "GROUP:Overall/Read:authenticated"
        - "GROUP:Job/Build:authenticated"
        - "GROUP:Job/Read:authenticated"
  remotingSecurity:
      enabled: true

security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: 'jfrog-creds'
          username: ${JFROG_ACCOUNT_USER}
          password: ${JFROG_ACCOUNT_PASSWORD}
          description: 'Docker Registry account (JFrog Artifactory)'
          scope: GLOBAL

unclassified:
  location:
    url: https://jenkins.lab.saschascherrer.de

tool:
  maven:
    installations:
    - name: "maven-3.6.3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.6.3"
              
jobs:
  - script: >
      pipelineJob('spring-petclinic') {
        logRotator(5, 20)
        definition {
          cpsScm {
              lightweight(true)
              scm {      
                  git {
                      remote {
                          url("https://github.com/saschascherrer/spring-petclinic.git")
                          branch("main")
                      }
                  }
              }
              scriptPath("jenkins-pipeline/Jenkinsfile")
          }
        }
        triggers {
          cron("H/15 3 1-5 * *")
        }
      }

