jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "USER:Overall/Administer:admin"
  remotingSecurity:
      enabled: true

security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy

unclassified:
  location:
    url: https://jenkins.lab.saschascherrer.de

jobs:
  - script: >
      pipelineJob('spring-petclinic') {
        logRotator(5, 2)
        definition {
          cpsScm {
              lightweight(true)
              scm {      
                  git {
                      remote {
                          url("https://github.com/saschascherrer/jenkins-ci-example.git")
                          branch("main")
                      }
                  }
              }
              scriptPath("jenkins-pipeline/Jenkinsfile")
          }
        }
        triggers {
          cron("H/15 3 1-5 * *")
        }
      }
